### ISSUE TITLE
:do ... while typo

### ISSUE THREAD

**Issue by nullmem** [phistrom/auto-bogons#1]
https://github.com/phistrom/auto-bogons/blob/64ea0d54d9014bb6417037c3703e8f4b713501b9/bogon-updater.rsc#L57

should be:

`    } while=($lineEnd < $contentLen - 2)`

**Comment by phistrom** [comment]
Thank you. You're absolutely correct, the [Scripting documentation on the Mikrotik Wiki](https://wiki.mikrotik.com/wiki/Manual:Scripting#Loops) clearly shows an equals sign after the `while` in a "`:do ... while`" loop.

I've been using this script in production without issue for quite some time. Commit 0faf1be fixes this typo though.

Out of curiosity, was there a particular version of RouterOS where this typo caused the script to fail?
